spring:
  main:
    banner-mode: off
    log-startup-info: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spatial_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: '1234'

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

logging:
  level:
    root: ERROR
    com.spatialidx: INFO